accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

tweeds/urls.py
from django.urls import path

from tweeds.views import (
    PostListView,
    create_post,
    create_comment
)

urlpatterns = [
    path("", PostListView.as_view(), name='home'),
    path("create/", create_post, name='create_post'),
    path("create/comment/", create_comment, name='create_comment')
]

tweedsies/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tweeds/", include("tweeds.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home")),
    ),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

tweeds/models.py
from django.db import models
from django.conf import settings


USER = settings.AUTH_USER_MODEL

# Create your models here.
class Post(models.Model):
    text = models.TextField()
    owner = models.ForeignKey(USER, related_name='posts', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text

class Comment(models.Model):
    text = models.TextField()
    owner = models.ForeignKey(USER, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey("Post", related_name='comments', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # form.save()
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

tweeds/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from sqlite3 import IntegrityError
from tweeds.models import Post, Comment


# Create your views here.
class PostListView(ListView):
    model = Post
    template_name = "posts/list.html"



@require_http_methods(["POST"])
def create_post(request):
    # get text from post request
    post_text = request.POST.get("post_text")
    # get user id
    requested_user = request.user

    try:
        # create post list item
        Post.objects.create(
            owner=requested_user, text=post_text
        )
    except IntegrityError:
        pass
    # redirect to current recipe page-which we get from the request
    return redirect("home")



@require_http_methods(["POST"])
def create_comment(request):
    # get comment from post request
    comment_text = request.POST.get("comment_text")
    post_id = request.POST.get("feed_post_id")
    post = Post.objects.get(id=post_id)
    print("thisssssss", post_id, comment_text)
    # get user id
    requested_user = request.user

    try:
        # create shopping list item
        Comment.objects.create(
            owner=requested_user, text=comment_text, post = post
        )
    except IntegrityError:
        pass
    # redirect to current recipe page-which we get from the request
    return redirect("home")

tweeds/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tweedsies</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
</head>
<body>
        <nav class="nav">
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% endif %}
                {% if user.is_authenticated == False %}
                <li>
                    <a href="{% url 'signup' %}">Signup</a>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    {% block content %}
    {% endblock content %}
    <div class="footer">
        <p>tweedsies.com</p>
    </div>
</body>
</html>

tweeds/templates/posts/list.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div class="side-bar">
            <img src="http://s3.amazonaws.com/pix.iemoji.com/images/emoji/apple/ios-12/256/front-facing-baby-chick.png" alt="" class="avator">
        </div>
        <div class="feed">
            <h1>Home</h1>
            <div>
                <form method="post" action="{% url 'create_post' %}">
                    {% csrf_token %} {{ form.as_p }}
                    <div>
                    <input
                        type="text"
                        name="post_text"
                        placeholder="What's going on?"
                    />
                    <button>Post</button>
                    </div>
                </form>
            </div>
            
            {% for post in post_list %}
            <div class="tweet-wrap">
                <div class="tweet-post">
                <img src="https://www.nicepng.com/png/detail/202-2024580_png-file-profile-icon-vector-png.png" alt="" class="avator">
                <div class="tweet-post-info">
                    {{ post.owner }} <span>@{{ post.owner }}</span><span>. {{ post.created }}</span>
                    <p>{{ post.text }}</p>
                </div>
                </div>
                <div class="tweet-comment">
                    <form method="post" action="{% url 'create_comment' %}">
                        {% csrf_token %} {{ form.as_p }}
                        <div>
                            <input
                            type="text"
                            name="comment_text"
                            placeholder="Care to comment?"
                            />
                            <input
                            type="hidden"
                            name="feed_post_id"
                            value="{{ post.id }}"
                            />
                            <button>Comment</button>
                        </div>
                    </form>
                    <div class="tweet-comment-wrap">
                        {% for comment in post.comments.all %}
                        <div class="tweet-comment-info">
                            <p>
                                <img src="http://clipart-library.com/new_gallery/70-705972_cute-clipart-baby-chicken-baby-chick-easter-cartoon.png" alt="" class="avator">
                                {{ comment.text }}</p>
                            {{ comment.owner }} <span>@{{ comment.owner }}</span><span>. {{ comment.updated }}</span>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </main>
{% endblock content %}